<div style="text-align: center; padding:5px; font-size: 1.5em; color: #cc4541; margin-bottom: 40px; text-decoration: underline;">Privacy Policy</div>

<div style='text-align:justify;'>
    <span style='font-weight:bold;'>Effective date: February 09, 2020</span><br>
    <br>
    <p>Cheyenne County Farmer's Market (“us”, “we”, or “our”) operates the <a href="http://cncofarmersmarket.com" target="_blank">http://cncofarmersmarket.com</a> website (hereinafter referred to as the “Service”).<br>
        This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.<br>
        We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.</p>
    <br>
    <span style='font-weight:bold;'>Definitions</span><br><br>
    <p style="margin-left: 10px;">Service</p>
    <p style="margin-left: 20px;">Service is the <a href="http://cncofarmersmarket.com" target="_blank">http://cncofarmersmarket.com</a> website operated by Cheyenne County Farmer's Market</p>
    <br>
    <p style="margin-left: 10px;">Personal Data</p>
    <p style="margin-left: 20px;">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
    <br>
    <p style="margin-left: 10px;">Usage Data</p>
    <p style="margin-left: 20px;">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
    <br>
    <p style="margin-left: 10px;">Cookies</p>
    <p style="margin-left: 20px;">Cookies are small files stored on your device (computer or mobile device).</p>
    <br>
    <span style='font-weight:bold;'>Information Collection and Use</span><br>
    <br>
    <p style="margin-left: 10px;">We collect several different types of information for various purposes to provide and improve our Service to you.</p>
    <br>
    <span style='font-weight:bold;'>Types of Data Collected</span><br>
    <br>
    <p style="margin-left: 10px;">Personal Data</p>
    <br>
    <p style="margin-left: 20px;">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
    <p style="margin-left: 20px;">Email address</p>
    <p style="margin-left: 20px;">First name and last name</p>
    <p style="margin-left: 20px;">Phone number</p>
    <p style="margin-left: 20px;">Address, State, Province, ZIP/Postal code, City</p>
    <p style="margin-left: 20px;">Cookies and Usage Data</p>
    <br>
    <p style="margin-left: 10px;">We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</p>
    <br>
    <p style="margin-left: 10px;">Usage Data</p>
    <br>
    <p style="margin-left: 20px;">We may also collect information on how the Service is accessed and used (“Usage Data”). This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
    <br>
    <p style="margin-left: 10px;">Tracking & Cookies Data</p>
    <br>
    <p style="margin-left: 20px;">We use cookies and similar tracking technologies to track log in activity on our Service by users with administrative access.<br>
    <p style="margin-left: 20px;">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
    <p style="margin-left: 20px;">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
    <br>
    <p style="margin-left: 10px;">Examples of Cookies we use:</p>
    <p style="margin-left: 20px;">Session Cookies. We use Session Cookies to operate our Service.</p>
    <p style="margin-left: 20px;">Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</p>
    <p style="margin-left: 20px;">Security Cookies. We use Security Cookies for security purposes.</p>
    <br>
    <span style='font-weight:bold;'>Use of Data</span><br>
    <br>
    <p style="margin-left: 10px;">Cheyenne County Farmer's Market uses the collected data for various purposes:</p>
    <p style="margin-left: 20px;">To provide and maintain our Service</p>
    <p style="margin-left: 20px;">To notify you about changes to our Service</p>
    <p style="margin-left: 20px;">To allow you to participate in interactive features of our Service when you choose to do so</p>
    <p style="margin-left: 20px;">To provide customer support</p>
    <p style="margin-left: 20px;">To gather analysis or valuable information so that we can improve our Service</p>
    <p style="margin-left: 20px;">To monitor the usage of our Service</p>
    <p style="margin-left: 20px;">To detect, prevent and address technical issues</p>
    <p style="margin-left: 20px;">To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or inquired about unless you have opted not to receive such information</p>
    <br>
    <span style='font-weight:bold;'>Transfer of Data</span><br>
    <br>
    <p style="margin-left: 10px;">Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
    <p style="margin-left: 10px;">If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>
    <p style="margin-left: 10px;">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
    <p style="margin-left: 10px;">Cheyenne County Farmer's Market will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
    <br>
    <span style='font-weight:bold;'>Disclosure of Data</span><br>
    <br>
    <p style="margin-left: 10px;">Legal Requirements</p>
    <br>
    <p style="margin-left: 10px;">Cheyenne County Farmer's Market may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
    <p style="margin-left: 20px;">To comply with a legal obligation.</p>
    <p style="margin-left: 20px;">To protect and defend the rights or property of Cheyenne County Farmer's Market.</p>
    <p style="margin-left: 20px;">To prevent or investigate possible wrongdoing in connection with the Service.</p>
    <p style="margin-left: 20px;">To protect the personal safety of users of the Service or the public.</p>
    <p style="margin-left: 20px;">To protect against legal liability</p>
    <br>
    <span style='font-weight:bold;'>Security of Data</span><br>
    <br>
    <p style="margin-left: 10px;">The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
    <br>
    <p style="margin-left: 10px;">Service Providers</p>
    <br>
    <p style="margin-left: 20px;">We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide the Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.</p>
    <p style="margin-left: 20px;">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
    <br>
    <p style="margin-left: 10px;">Analytics</p>
    <br>
    <p style="margin-left: 10px;">We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
    <p style="margin-left: 10px;">Google Analytics</p>
    <p style="margin-left: 20px;">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
    <p style="margin-left: 20px;">You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.</p>
    <p style="margin-left: 20px;">For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en" target="_blank">https://policies.google.com/privacy?hl=en</a></p>
    <br>
    <span style='font-weight:bold;'>Payments</span><br>
    <br>
    <p style="margin-left: 10px;">We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
    <p style="margin-left: 10px;">We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
    <p style="margin-left: 10px;">The payment processors we work with are:</p>
    <p style="margin-left: 20px;">Authorize.net</p>
    <p style="margin-left: 20px;">Their Privacy Policy can be viewed at <a href="https://www.authorize.net/company/privacy/" target="_blank">https://www.authorize.net/company/privacy/</a></p>
    <br>
    <span style='font-weight:bold;'>Links to Other Sites</span><br>
    <br>
    <p style="margin-left: 10px;">Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
    <p style="margin-left: 10px;">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
    <br>
    <span style='font-weight:bold;'>Children’s Privacy</span><br>
    <br>
    <p style="margin-left: 10px;">Our Service does not address anyone under the age of 18 (“Children”).</p>
    <p style="margin-left: 10px;">We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
    <br>
    <span style='font-weight:bold;'>Changes to This Privacy Policy</span><br>
    <br>
    <p style="margin-left: 10px;">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
    <p style="margin-left: 10px;">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” at the top of this Privacy Policy.</p>
    <p style="margin-left: 10px;">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
    <br>
    <span style='font-weight:bold;'>Contact Us</span><br>
    <br>
    <p style="margin-left: 10px;">If you have any questions about this Privacy Policy, please contact us:</p>
    <p style="margin-left: 20px;">By email: coordinator@cncofarmersmarket.com</p>
    <p style="margin-left: 20px;">By visiting this page on our website: <a href="http://cncofarmersmarket.com/index.php?page=privacyPolicy" target="_self">http://cncofarmersmarket.com/index.php?page=privacyPolicy</a></p>
</div>